### ISSUE TITLE
Wakfu Mod Loader - Version 1.2.0

### ISSUE THREAD

**Issue by DreamSworK** [Valianton/Wakfu-Translate#11]
Привет! Обновилась версия загрузчика модов.
Старый формат настроек не совместим с новой версией, там конечно небольшие изменения, но всё таки они есть и со старыми настройками работать не будет.
К сообщению прикрепляю новый файл настроек, замени у себя пожалуйста и обнови версию мода, чтобы я мог применить изменения.
[rus.ini.zip](https://github.com/Valianton/Wakfu-Translate/files/1034153/rus.ini.zip)

**Comment by DreamSworK** [comment]
**_rus.ini_**
```ini
[modifications]
1\target=game
1\before=~ m/-L \\w{2}/
1\after=-L ru
1\type=command

2\target=game
2\before=
2\after=-c %WORK_DIRECTORY%/config.properties
2\type=command

3\target=%MAIN_APPLICATION_DIRECTORY%/config.properties
3\before=themeDirectory=jar:file:./contents/gui_jar/gui.jar!/
3\after=themeDirectory=jar:file:%WORK_DIRECTORY%/gui.jar!/
3\type=settings

4\target=%MODS_DIRECTORY%/rus/fonts.jar
4\before=%MAIN_APPLICATION_DIRECTORY%/contents/gui_jar/gui.jar
4\after=%WORK_DIRECTORY%/gui.jar
4\type=jar

5\target=%MAIN_APPLICATION_DIRECTORY%/config.properties
5\before=i18nPath=jar:file:./contents/i18n/i18n.jar!/texts
5\after=i18nPath=jar:file:%WORK_DIRECTORY%/i18n.jar!/texts
5\type=settings

6\target=%MODS_DIRECTORY%/rus/texts_ru.properties
6\before=
6\after=%WORK_DIRECTORY%/i18n_ru.jar
6\type=jar

size=6
```

**Comment by Valianton** [comment]
Готово

**Comment by DreamSworK** [comment]
Версию пропиши 1.6.6 в **_package.xml_** иначе не получится обновление, инсталлятор не увидит новую версию

**Comment by Valianton** [comment]
Готово

**Comment by DreamSworK** [comment]
Если вдруг у людей будут проблемы, связанные с тем, что что не работает руссификация. Пусть кроме мода русификации обязательно обновят и плагин-загрузчик модов.
