### ISSUE TITLE
Неправильный перевод имени Astrub Knight

### ISSUE THREAD

**Issue by Valianton** [Valianton/Wakfu-Translate#9]
> В Аструбе, второй квест (сходить, потренироваться на манекене). НПЦ, который там стоит - Astrub Knight. Переведен как "Аструб Найт" в описании квеста (когда его берешь). При этом сам НПЦ переведен корректно, Аструбский Рыцарь

Аполлония Карастелева

**Comment by Kvisenok** [comment]
Там подали хорошую идею - создать в вк дополнительное обсуждение "баг-репорт", пусть народ туда отписывает по поводу найденных ошибок.

**Comment by Valianton** [comment]
https://github.com/Valianton/Wakfu-Translate/commit/5eab29741594a01101c3d7a469189afd27c0fc99#diff-16aa262ef1dc048490c51184948cc512R197632

Исправлено, к сожалению словосочетание Аструбский Рыцарь найти не смогли
